### ISSUE TITLE
XCode 10.2 Build Error Swift 3 unsupported

### ISSUE THREAD

**Issue by BradPatras** [Marxon13/M13Checkbox#139]
After updating to XCode 10.2, project containing M13Checkbox via cocoapods is failing build with this message:

> SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'M13Checkbox')

<img width="596" alt="Screen Shot 2019-04-05 at 2 27 05 PM" src="https://user-images.githubusercontent.com/7176921/55652180-6745d080-57b0-11e9-9ed8-784435db274c.png">

**Comment by andreaantonioni** [comment]
Xcode 10.2 drops the support for Swift 3.0, that's why your're getting that error (https://developer.apple.com/documentation/xcode_release_notes/xcode_10_2_release_notes/swift_5_release_notes_for_xcode_10_2)

I would suggest you to update your codebase to Swift 4/4.2/5. Here is the official guide : https://swift.org/migration-guide-swift5/

**Comment by BradPatras** [comment]
My codebase is updated to swift 4.2.

**Comment by andreaantonioni** [comment]
Mmmmm ok, check this out. Go to:
Project ► M13CHeckbox ► Build Settings ► (Type 'swift' in Searchbar) Swift Compiler Language ► Swift Language Version

and check that the swift version is 4.2

**Comment by BradPatras** [comment]
Didn't realize we had a script in our podfile to specify a swift version, updated that and after pod update I no longer have any issues! Thanks
