### ISSUE TITLE
Cocoapods-generated Swift bridging header doesn't include all M13Checkbox methods/properties

### ISSUE THREAD

**Issue by churowa** [Marxon13/M13Checkbox#42]
I've included M13Checkbox (v 2.1.0) as a pod in an Objective-c project. The pod seems to install correctly, certainly well enough to integrate it in the storyboard. 

I just noticed that when I tried to call `setCheckState(newState: CheckState, animated: Bool)` on a checkbox in a UIView subclass, the compiler doesn't seem to know anything about the method. 

I had a look at the swift bridging header that was generated, and it looks like it's missing a few things. https://gist.github.com/churowa/66f54a984d58f2b8ecdb8f60602f6af5

Just comparing it to the available properties in M13Checkbox.swift, I see right away that it's missing `setCheckState`, `boxType`, `stateChangeAnimation`, and a few others.

Am I correct that it looks odd? I'm not sure what to look at next, basically.  I don't know that this is an M13Checkbox issue per se... Maybe it's more to do with Cocoapods or Xcode itself. But does the bridging header look right?

**Comment by AliSoftware** [comment]
@churowa It seems like all the properties you're talking about (`CheckState`, `BoxType`, and functions using those types as parameters like `setCheckState(_:animated:)`) are not `@objc`-compatible.

For example `CheckState` and `BoxType` are both `enum` with a `String` rawValue, which has no equivalent in / is not bridgeable to Objective-C. That's why Xcode won't be able to generate an equivalent declaration in the Bridging Header.

To fix that, either the M13Checkbox library needs to change its API so it uses types in its public API that are all `@objc`-compatible (which seems unlikely as it will probably mean to drop some features or change the lib architecture), or you'll have to create a wrapper around it that only exposes ObjC-compatible types so you can use it from ObjC, or you'll have to use it only from Swift.

**Comment by churowa** [comment]
Thanks! That's a wonderful explanation. Makes sense.

@Marxon13 I assume you're not interested in making this library objective-c compatible? I'll probably just use a wrapper.

**Comment by churowa** [comment]
Closing because I can't read minimum requirements.
