### ISSUE TITLE
Checkmark keep repeating in another tableviewcell row

### ISSUE THREAD

**Issue by reza355** [Marxon13/M13Checkbox#80]
Hi, i tried to using m13checkbox in tableview cell and its working well. but the problem is, when i made a checkmark in one row, there's will be another row which automaticly checkmarked (example if i make a checkmark in 3 rows, there's will be another 3 mark below that checkmark that i made). here is my cell code:

`@IBOutlet weak var checkBoxView: UIView!
    @IBOutlet weak var directionDescLbl: UILabel!

    override func layoutSubviews() {
        super.layoutSubviews()
        let checkBox = M13Checkbox(frame: CGRect(x: 0.0, y: 0.0, width: 40.0, height: 40.0))
        checkBoxView.addSubview(checkBox)
    }
    
    func configureCell(post: DirectionData){
        directionDescLbl.text = post.directionDesc
    }`

thanks

**Comment by Marxon13** [comment]
It looks like its because you are adding the checkbox to the cell in `layoutSubviews()` and not one of the initializers. Each time that method is called, a new checkbox will be added. You could easily end up with a view with over a hundred checkboxes in it.

With cell's I would also reset the state of the checkbox in the cell's `prepareForReuse()` method.
